#!/usr/bin/env bash

# Transfers a file from Holberton's client to another.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory on the server
scp $SCP_OPTIONS -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "Error transferring the file."
fi
