#!/usr/bin/env bash

# Script to install and configure Nginx on a remote server

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

export SCP_OPTIONS="-o StrictHostKeyChecking=no"

scp $SCP_OPTIONS -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"

if [ $? -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "Error transferring the file."
fi

sudo apt update
sudo apt install nginx

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default


sudo service nginx restart

curl -s http://localhost | grep -q "Hello World!"
if [ $? -eq 0 ]; then
    echo "Nginx is working correctly!"
else
    echo "Nginx configuration issue. Check your setup."
fi
