#!/usr/bin/env bash

# Installs and setup haproxy

apt-get update
apt-get install -y software-properties-common

add-apt-repository -y ppa:vbernat/haproxy-1.8

apt-get update

apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Listen to web1 and web2 servers

cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg

listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 452223-web-01 54.173.191.2 check
    server 452223-web-02 52.86.100.143 check
EOF

sudo service haproxy restart
