#!/usr/bin/env bash

apt-get update -y && apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80;/g; s/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default
ufw allow 80/tcp
service nginx restart
