#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash
# Not allowed to use ps

for pid in $(pgrep -f bash); do
    name=$(cat /proc/$pid/comm)
    echo "$pid - $name" 
done
